#!/bin/sh
#
# @name Gazebo-classic Iris FTC
#
# @type Quadrotor Wide
#
# @maintainer Chanbeom Lee
#

# Reuse the classic iris model and output routing, then layer the
# fault-tolerant-control defaults used for the gz x500 experiments.
. ${R}etc/init.d-posix/airframes/10015_gazebo-classic_iris

param set-default CA_FTC_EN 1
param set-default CA_FTC_TYPE 1
param set-default CA_FTC_MOT 3
param set-default CA_FTC_LOE 0.68
param set-default CA_FTC_TRIG_MODE 1
param set-default CA_FTC_STATE 0
param set-default CA_FTC_ALC_MODE 1

# CA_FTC_YAW_SCL is intentionally left at its module default because the
# current allocator implementation does not consume it yet.
