#!/bin/sh
#
# @name Gazebo x500
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.22
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.20
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.22
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.20
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

param set-default CA_FTC_EN 1
param set-default CA_FTC_TYPE 1
param set-default CA_FTC_MOT 2
param set-default CA_FTC_LOE 0.0
param set-default CA_FTC_TRIG_MODE 1
param set-default CA_FTC_STATE 0
param set-default CA_FTC_YAW_SCL 1.0
param set-default CA_FTC_ALC_MODE 1
param set-default CA_FTC_DUAL_EN 0
param set-default CA_FTC_INDI_EN 1
param set-default CA_FTC_INDI_SDL 0.0
param set-default CA_FTC_INDI_DUL 0.0
param set-default CA_FTC_INDI_K1 8.0
param set-default CA_FTC_INDI_K2 8.0
param set-default CA_FTC_INDI_K3 8.0
param set-default CA_FTC_INDI_FC 15.0
param set-default MC_FTC_INDI_EN 1
param set-default MC_FTC_NX 0.20
param set-default MC_FTC_NY 0.20
param set-default MC_FTC_NZ -0.96
param set-default MC_FTC_KX 3.0
param set-default MC_FTC_KY 3.0
param set IMU_INTEG_RATE 500
param set IMU_GYRO_RATEMAX 500

param set-default MPC_THR_HOVER 0.60
param set-default NAV_DLL_ACT 2
