#!/bin/sh
#
# @name Gazebo Iris FTC
#
# @type Quadrotor Wide
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=iris_ftc_default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=iris_ftc}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.20
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.20
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.20
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.20
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MIN4 0
param set-default SIM_GZ_EC_MAX1 2000
param set-default SIM_GZ_EC_MAX2 2000
param set-default SIM_GZ_EC_MAX3 2000
param set-default SIM_GZ_EC_MAX4 2000

param set-default CA_FTC_EN 1
param set-default CA_FTC_TYPE 1
param set-default CA_FTC_MOT 2
param set-default CA_FTC_LOE 0.0
param set-default CA_FTC_TRIG_MODE 1
param set-default CA_FTC_STATE 0
param set-default CA_FTC_ALC_MODE 1
param set-default CA_FTC_DUAL_EN 0
param set-default CA_FTC_INDI_EN 1
param set-default CA_FTC_KF 0.00000584
param set-default CA_FTC_OMAX 2000.0
param set-default CA_FTC_ERPMAX 6000.0
param set-default CA_FTC_INDI_SDL 50.0
param set-default CA_FTC_INDI_DUL 0.0
param set-default CA_FTC_INDI_K1 4.0
param set-default CA_FTC_INDI_K2 4.0
param set-default CA_FTC_INDI_K3 0.1
param set-default CA_FTC_INDI_FC 5.0
param set-default CA_FTC_INDI_ILIM 1.0
param set-default CA_FTC_INDI_M 1.5
param set-default CA_FTC_INDI_IX 0.029125
param set-default CA_FTC_INDI_IY 0.029125
param set-default MC_FTC_INDI_EN 1
param set-default MC_FTC_NX 0.20
param set-default MC_FTC_NY 0.20
param set-default MC_FTC_NZ -0.96
param set-default MC_FTC_KX 3.0
param set-default MC_FTC_KY 3.0
param set-default MC_ROLLRATE_MAX 360.0
param set-default MC_PITCHRATE_MAX 360.0
param set-default MPC_THR_HOVER 0.44

# Force persisted SITL params to stay aligned with the iris_ftc GZ motor model.
param set SIM_GZ_EC_MIN1 0
param set SIM_GZ_EC_MIN2 0
param set SIM_GZ_EC_MIN3 0
param set SIM_GZ_EC_MIN4 0
param set SIM_GZ_EC_MAX1 2000
param set SIM_GZ_EC_MAX2 2000
param set SIM_GZ_EC_MAX3 2000
param set SIM_GZ_EC_MAX4 2000
param set CA_FTC_OMAX 2000.0
param set CA_FTC_INDI_M 1.5
param set CA_FTC_INDI_IX 0.029125
param set CA_FTC_INDI_IY 0.029125
param set MPC_THR_HOVER 0.44
param set IMU_INTEG_RATE 512
param set IMU_GYRO_RATEMAX 512
